name: 'Send Pull Requests info GitHub Action'
description: 'Notify new Pull Request into the server'
inputs:
  github-token:
    description: 'GitHub token is required to push our commits into your pull requests.'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'