name: 'Send Pull Requests info GitHub Action'
description: 'Notify new Pull Request into the server'
inputs:
  diff:
    description: 'Result of git diff'
    required: true
  sha:
    description: 'SHA is used to identify your commit'
    required: true
  collection:
    description: 'Collection name on storege'
    required: true
runs:
  using: 'node16'
  main: 'index.js'